version: '3'

services:
  postgres:
    image: postgres
    container_name: finance-app-postgres
    environment:
        POSTGRES_PASSWORD: pedro2012
        POSTGRES_USER: postgres
        POSTGRES_DB: finance-app
    ports:
    - "5432:5232"
    volumes:
    - ./postgres-data:/var/lib/postgresql/data

